version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  perl:
    build:
      context: ./perl
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      PORT: 80
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  ruby:
    build:
      context: ./ruby
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react_go:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - go
    links:
      - go
    environment:
      API: http://go:80
    ports:
      - "10001:443"
  react_perl:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - perl
    links:
      - perl
    environment:
      API: http://perl:80
    ports:
      - "10002:443"
  react_python:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - python
    links:
      - python
    environment:
      API: http://python:80
    ports:
      - "10003:443"
  react_php:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - php
    links:
      - php
    environment:
      API: http://php:80
    ports:
      - "10004:443"
  react_nodejs:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - nodejs
    links:
      - nodejs
    environment:
      API: http://nodejs:80
    ports:
      - "10005:443"
  react_ruby:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - ruby
    links:
      - ruby
    environment:
      API: http://ruby:80
    ports:
      - "10006:443"
