version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
    ports:
      - "3306:3306"
  redis:
    extends:
      file: docker-compose-redis.yml
      service: redis
  go_dev:
    build:
      context: ./go/src/app
      dockerfile: Dockerfile-dev
    volumes:
      - ./go/src/app:/go/src/github.com/isucon/isucon6-final/webapp/go
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    environment:
      ISUCON_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      REDIS_URL: redis://redis:6379
  react_dev:
    extends:
      file: docker-compose-react.yml
      service: react_dev
    depends_on:
      - go_dev
    links:
      - go_dev
    environment:
      API: http://go_dev:8080
    ports:
      - "8080:443"
